"""Shared configuration for Phase 2 routing experiments.

Task A1 (Abdul Raheem): routing data matrix builder.
All paths are relative to the repository root so the package works from any
working directory. Generated artifacts live in routing/data and
routing/results (both gitignored - regenerated by the scripts).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ALIGNED8_DIR = ROOT / "cleaned" / "aligned_8_models"
ALIGNED7_DIR = ROOT / "cleaned" / "aligned_7_models"
OUT_DIR = Path(__file__).resolve().parent / "data"
RESULTS_DIR = Path(__file__).resolve().parent / "results"

# Cheapest -> strongest ordering (used by cascade logic and table display).
MODELS = [
    "Llama-3.1-8B-Instruct",
    "Qwen3-8B",
    "deepseek-v3-0324",
    "gemini-2.5-flash",
    "gpt-4.1",
    "claude-sonnet-4",
    "gemini-2.5-pro",
    "gpt-5",
]

STRONGEST = "gpt-5"
CHEAPEST = "Llama-3.1-8B-Instruct"

# Oracle objective: minimize cost + ALPHA * latency among models that answer
# correctly. The sweep below is reported in the headline table.
ALPHA_SWEEP = [0.0, 0.001, 0.002, 0.005, 0.01]

# Default operating point used by the practical routers (A3): trades a small
# amount of cost for substantially lower latency in the oracle sweep (A2).
ALPHA = 0.002

# Thesis target: practical routers must keep at least this fraction of the
# always-strongest policy's accuracy (A_min = 90% in the master doc).
QUALITY_FLOOR = 0.90

SEED = 42
