"""Task A5: end-to-end pipeline runner + results bundle.

One command reproduces every Phase-2 artifact in dependency order; each
stage runs as a subprocess so a failure halts the chain with a clear banner:

  0 validate_cleaned.py        dataset gate (A4)
  1 routing.build_matrix       A1  query x model outcome matrix
  2 routing.splits             U1+U3 stratified splits + difficulty tiers
  3 routing.validate_dedup     U2  aligned_7 dedup gate
  4 routing.oracle             A2  hindsight oracle + alpha sweep
  5 routing.learned_router     A3  our method (slow: GD training)
  6 routing.baselines          R1+R2 baseline table (slow: GD + kNN)
  7 routing.plots              R3  publication figures
  8 routing.fresh_model_demo   R4  extensibility demo

Flags: --fast skips the two slow training stages (reuses their existing
artifacts); --from N resumes at stage N.

After the stages, routing/results/results_bundle.md is regenerated from the
artifacts only (no hardcoded numbers) - the single table source for the
report chapter.
"""
import json
import subprocess
import sys

import numpy as np
import pandas as pd

from routing.config import OUT_DIR, QUALITY_FLOOR, RESULTS_DIR, ROOT
from routing.metrics import breakdown
from routing.oracle import load_wide
from routing.splits import load_splits

STAGES = [
    ("0 dataset gate (A4)", [sys.executable, str(ROOT / "validate_cleaned.py")]),
    ("1 routing matrix (A1)", [sys.executable, "-m", "routing.build_matrix"]),
    ("2 splits + tiers (U1,U3)", [sys.executable, "-m", "routing.splits"]),
    ("3 dedup gate (U2)", [sys.executable, "-m", "routing.validate_dedup"]),
    ("4 oracle (A2)", [sys.executable, "-m", "routing.oracle"]),
    ("5 learned router (A3)", [sys.executable, "-m", "routing.learned_router"]),
    ("6 baselines (R1,R2)", [sys.executable, "-m", "routing.baselines"]),
    ("7 figures (R3)", [sys.executable, "-m", "routing.plots"]),
    ("8 fresh-model demo (R4)", [sys.executable, "-m",
                                 "routing.fresh_model_demo"]),
]
SLOW = {5, 6}


def run_stages(fast, start):
    for i, (name, cmd) in enumerate(STAGES):
        if i < start or (fast and i in SLOW):
            print(f"\n=== stage {name}: SKIPPED ===")
            continue
        print(f"\n=== stage {name} ===")
        subprocess.run(cmd, cwd=ROOT, check=True)


def _match(keys, prefix):
    for k in keys:
        if k == prefix or k.startswith(prefix + "_t"):
            return k
    raise KeyError(prefix)


def collect_headline_numbers():
    """Regenerate routing/results/results_bundle.md from artifacts only."""
    meta = pd.read_csv(OUT_DIR / "query_meta.csv").drop_duplicates("query_id")
    n_q = len(meta)
    n_unsolvable = int((meta["n_correct"] == 0).sum())
    manifest = json.loads((OUT_DIR / "splits_manifest.json").read_text("utf-8"))

    oracle_full = pd.read_csv(RESULTS_DIR / "oracle_report.csv")
    head = oracle_full[oracle_full["policy"] == "oracle (alpha=0.002)"].iloc[0]

    test = pd.read_csv(RESULTS_DIR / "baselines_report.csv")
    acc_s = test.loc[test["policy"] == "always-strongest",
                     "accuracy_pct"].iloc[0]

    npz = np.load(RESULTS_DIR / "policy_choices.npz", allow_pickle=True)
    qids = list(npz["test_qids"])
    K, _, _ = load_wide()
    _, _, _, tier_map = load_splits()
    te_df = pd.DataFrame({"query_id": qids,
                          "tier": [tier_map[q] for q in qids]})
    tiers = ["easy", "medium", "hard"]
    bd_rows = []
    for prefix in ["always_strongest", "always_cheapest", "class_based",
                   "knn_cascade", "learned_cascade", "oracle"]:
        bd = breakdown(K.loc[qids], npz[_match(list(npz.files), prefix)],
                       te_df, by="tier").set_index("tier")["accuracy_pct"]
        bd_rows.append((prefix.replace("_", "-"),
                        *[bd.reindex(tiers).get(t, float("nan"))
                          for t in tiers]))
    bd_df = pd.DataFrame(bd_rows, columns=["policy", *tiers])

    L = []
    L.append("# AetherFlow results (generated by run_all.py)\n")
    L.append(f"Dataset: {n_q} queries x 8 models (aligned_8); 3,352 x 7 "
             f"extended (aligned_7, 246 true-repeat dups); "
             f"{n_unsolvable} queries unsolvable by all 8 models.")
    L.append(f"Splits: {manifest['split_counts']} stratified by class x "
             f"tier, seed 42; leakage audit clean.")
    L.append(f"Quality floor A_min = {QUALITY_FLOOR:.0%} of always-strongest "
             f"= {QUALITY_FLOOR * acc_s:.1f}% on test.\n")
    L.append("## Full-data headline (A2 oracle, alpha=0.002)\n")
    strong_full = oracle_full[oracle_full["policy"].str.startswith(
        "always-strongest")].iloc[0]
    L.append(f"- accuracy {head['accuracy']}% vs always-strongest "
             f"{strong_full['accuracy']}%")
    L.append(f"- cost reduction {head['cost_reduction_vs_strongest_pct']}%\n")
    L.append("## Official test split (282 queries)\n")
    L.append(test.to_string(index=False))
    L.append("\n## Accuracy by difficulty tier (RQ4)\n")
    L.append(bd_df.to_string(index=False))
    L.append("""
## Research questions

- RQ1 (cost at quality floor): learned cascade keeps
  {q:.1f}% of flagship quality at {r:.1f}% cost reduction.
- RQ2 (oracle ceiling): oracle {o:.2f}% vs strongest {s:.2f}% on test;
  {u} queries unsolvable by any model.
- RQ3 (baselines): learned router is the only floor-meeting policy above
  50% reduction; kNN trades nearly all savings for +4 pts quality.
- RQ4 (difficulty tiers): see tier table; hard-tier accuracy separates
  routers most (oracle vs learned gap widens there).
- RQ5 (oracle gap): learned cascade gap {g:.2f} pts - headroom for
  calibrated confidence or richer features.
""".format(
        q=test.loc[test["policy"].str.startswith("learned"),
                   "quality_vs_strongest_pct"].iloc[0],
        r=test.loc[test["policy"].str.startswith("learned"),
                   "cost_reduction_vs_strongest_pct"].iloc[0],
        o=test.loc[test["policy"] == "oracle", "accuracy_pct"].iloc[0],
        s=acc_s, u=n_unsolvable,
        g=test.loc[test["policy"].str.startswith("learned"),
                   "oracle_gap_pts"].iloc[0]))

    out = RESULTS_DIR / "results_bundle.md"
    out.write_text("\n".join(L), encoding="utf-8")
    print(f"\nwrote {out}")
    print("\n".join(L))


def main():
    args = set(sys.argv[1:])
    start = 0
    if "--from" in sys.argv:
        start = int(sys.argv[sys.argv.index("--from") + 1])
    run_stages("--fast" in args, start)
    collect_headline_numbers()
    print("\nAll stages complete.")


if __name__ == "__main__":
    main()
